In [1]:
# 1.Write a Python Program to Add Two Matrices?

import numpy as np

arr1 = np.random.randint(1,3,(4,2))
arr2 = np.random.randint(1,3,(4,2))
print(f'first matrice{arr1}\n Second matrice {arr2}')
print('Add two Marrices:\n',arr1+arr2)

first matrice[[1 1]
 [2 2]
 [1 2]
 [1 2]]
 Second matrice [[2 1]
 [2 2]
 [1 2]
 [1 2]]
Add two Marrices:
 [[3 2]
 [4 4]
 [2 4]
 [2 4]]


In [2]:
# 2.Write a Python Program to Multiply Two Matrices?


import numpy as np

arr1 = np.random.randint(1,4,(4,4))
arr2 = np.random.randint(1,4,(4,4))
print(f'first matrice{arr1}\n Second matrice {arr2}')
print('Add two Marrices:\n',arr1@arr2)

first matrice[[3 1 3 1]
 [2 3 3 3]
 [3 2 1 1]
 [3 2 1 1]]
 Second matrice [[3 3 2 3]
 [3 3 3 2]
 [1 1 3 3]
 [3 2 1 2]]
Add two Marrices:
 [[18 17 19 22]
 [27 24 25 27]
 [19 18 16 18]
 [19 18 16 18]]


In [3]:
# 3.Write a Python Program to Transpose a Matrix?

import numpy as np

matrix =  np.array([[1,2,3],[4,5,6]])
print(matrix)
matrix.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
# 4. Write a Python Program to Sort Words in Alphabetic Order?

lst = ['Delhi','Gurugon','Noida','Jaipur','Kota','c','a','f']
order_Alpha = sorted(lst)
order_Alpha

['Delhi', 'Gurugon', 'Jaipur', 'Kota', 'Noida', 'a', 'c', 'f']

In [5]:
# 5.Write a Python Program to Remove Punctuation From a String?
import string as st
def remove(txt):
    for pun in st.punctuation:
        txt = txt.replace(pun,'')
    print(txt)
        
txt = "I have to go# somewhere$%"
remove(txt)

I have to go somewhere
